# Generated by Django 2.2.4 on 2019-11-17 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0006_auto_20191117_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
    ]
