# Generated by Django 2.2.4 on 2019-11-18 15:18

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0008_auto_20191118_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='PNG', keep_meta=True, quality=75, size=[215, 215], upload_to='items'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', keep_meta=True, null=True, quality=75, size=[80, 80], upload_to='profile'),
        ),
    ]
